name: hello-world
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        
      - name: print index.html
        run: 
          cat index.html
          echo " this work flow triggered by ${{ github.actor }} "
          echo " this repo name is ${{ github.repository }} "
          echo " this repo is on ${{ github.branch }} "  